import YAML from "yaml";
import type {
  LinuxDockerPoolConfig,
  ResolvedLinuxDockerConfig
} from "./linux-docker-config.js";
import type { DeploymentEnv } from "./env.js";

export function renderLinuxDockerCompose(
  config: ResolvedLinuxDockerConfig,
  env: DeploymentEnv
): string {
  const services = Object.fromEntries(
    config.pools.flatMap((pool) =>
      Array.from({ length: pool.size }, (_, index) => {
        const serviceName = buildLinuxDockerServiceName(pool, index);
        return [serviceName, renderService(pool, index)];
      })
    )
  );

  const document = new YAML.Document({
    name: `${env.composeProjectName}-linux-docker`,
    services
  });

  return [
    "# Generated by pnpm render-linux-docker-compose",
    "# Linux Docker runners: dedicated Docker host, ephemeral one-job runners, explicit Docker socket mount.",
    document.toString().trimEnd()
  ].join("\n");
}

export function buildLinuxDockerServiceName(
  pool: LinuxDockerPoolConfig,
  index: number
): string {
  return `${pool.key}-runner-${formatIndex(index)}`;
}

export function buildLinuxDockerRunnerStateDir(
  pool: LinuxDockerPoolConfig,
  index: number
): string {
  return `${pool.runnerRoot}/runner-${formatIndex(index)}`;
}

function renderService(
  pool: LinuxDockerPoolConfig,
  index: number
): Record<string, unknown> {
  const runnerStateDir = buildLinuxDockerRunnerStateDir(pool, index);
  const runnerWorkDir = `${runnerStateDir}/_work`;
  const runnerTempDir = `${runnerStateDir}/_temp`;
  const runnerToolCache = `${runnerStateDir}/toolcache`;
  const environment: Record<string, string> = {
    GITHUB_PAT: "${GITHUB_PAT}",
    GITHUB_API_URL: "${GITHUB_API_URL:-https://api.github.com}",
    GITHUB_ORG: pool.organization,
    RUNNER_SCOPE: "organization",
    RUNNER_NAME: buildLinuxDockerServiceName(pool, index),
    RUNNER_GROUP: pool.runnerGroup,
    RUNNER_LABELS: pool.labels.join(","),
    RUNNER_VISIBILITY: pool.visibility,
    RUNNER_REPOSITORY_ACCESS: pool.repositoryAccess,
    RUNNER_STATE_DIR: runnerStateDir,
    RUNNER_LOG_DIR: `${runnerStateDir}/logs`,
    RUNNER_WORK_DIR: runnerWorkDir,
    RUNNER_TEMP: runnerTempDir,
    RUNNER_TOOL_CACHE: runnerToolCache,
    AGENT_TOOLSDIRECTORY: runnerToolCache,
    RUNNER_EXEC_MODE_OVERRIDE: "root",
    RUNNER_EPHEMERAL: "true",
    RUNNER_DISABLE_UPDATE: "true",
    DOCKER_HOST: "unix:///var/run/docker.sock"
  };

  if (pool.repositoryAccess === "selected") {
    environment.RUNNER_ALLOWED_REPOSITORIES = pool.allowedRepositories.join(",");
  }

  const service: Record<string, unknown> = {
    image: pool.imageRef,
    container_name: buildLinuxDockerServiceName(pool, index),
    hostname: buildLinuxDockerServiceName(pool, index),
    restart: "unless-stopped",
    stop_grace_period: "2m",
    environment,
    volumes: [
      `${runnerStateDir}:${runnerStateDir}`,
      "/var/run/docker.sock:/var/run/docker.sock"
    ],
    labels: {
      "com.github-runner-fleet.pool": pool.key,
      "com.github-runner-fleet.plane": "linux-docker",
      "com.github-runner-fleet.visibility": pool.visibility,
      "com.github-runner-fleet.repository-access": pool.repositoryAccess,
      "com.github-runner-fleet.allowed-repositories":
        pool.repositoryAccess === "all"
          ? "all"
          : pool.allowedRepositories.join(","),
      "com.github-runner-fleet.docker-capable": "true"
    }
  };

  if (pool.architecture !== "auto") {
    service.platform = `linux/${pool.architecture}`;
  }

  if (pool.resources.cpus) {
    service.cpus = pool.resources.cpus;
  }

  if (pool.resources.pidsLimit !== undefined) {
    service.pids_limit = pool.resources.pidsLimit;
  }

  if (pool.resources.memory) {
    service.mem_limit = pool.resources.memory;
  }

  return service;
}

function formatIndex(index: number): string {
  return String(index + 1).padStart(2, "0");
}
