import path from "node:path";
import YAML from "yaml";
import type { DeploymentEnv } from "./env.js";
import type {
  ResolvedWindowsDockerConfig,
  WindowsDockerPoolConfig
} from "./windows-config.js";

export function renderWindowsDockerCompose(
  config: ResolvedWindowsDockerConfig,
  env: DeploymentEnv
): string {
  const services = Object.fromEntries(
    config.pools.flatMap((pool) =>
      Array.from({ length: pool.size }, (_unused, index) => {
        const serviceName = buildWindowsDockerServiceName(pool, index);
        return [serviceName, renderService(pool, index)];
      })
    )
  );

  const document = new YAML.Document({
    name: `${env.composeProjectName}-windows-docker`,
    services
  });

  return [
    "# Generated by pnpm render-windows-compose",
    "# Windows Docker runners: dedicated Windows host, ephemeral one-job runners, explicit Docker named-pipe mount.",
    document.toString().trimEnd()
  ].join("\n");
}

export function buildWindowsDockerServiceName(
  pool: WindowsDockerPoolConfig,
  index: number
): string {
  return `${pool.key}-runner-${formatIndex(index)}`;
}

export function buildWindowsDockerRunnerStateDir(
  pool: WindowsDockerPoolConfig,
  index: number
): string {
  return path.win32.join(pool.runnerRoot, `runner-${formatIndex(index)}`);
}

function renderService(
  pool: WindowsDockerPoolConfig,
  index: number
): Record<string, unknown> {
  const runnerStateDir = buildWindowsDockerRunnerStateDir(pool, index);
  const runnerWorkDir = path.win32.join(runnerStateDir, "_work");
  const runnerTempDir = path.win32.join(runnerStateDir, "_temp");
  const runnerToolCache = path.win32.join(runnerStateDir, "toolcache");
  const serviceName = buildWindowsDockerServiceName(pool, index);
  const environment: Record<string, string> = {
    GITHUB_PAT: "${GITHUB_PAT}",
    GITHUB_API_URL: "${GITHUB_API_URL:-https://api.github.com}",
    GITHUB_ORG: pool.organization,
    RUNNER_SCOPE: "organization",
    RUNNER_NAME: serviceName,
    RUNNER_GROUP: pool.runnerGroup,
    RUNNER_LABELS: pool.labels.join(","),
    RUNNER_VISIBILITY: pool.visibility,
    RUNNER_REPOSITORY_ACCESS: pool.repositoryAccess,
    RUNNER_STATE_DIR: runnerStateDir,
    RUNNER_LOG_DIR: path.win32.join(runnerStateDir, "logs"),
    RUNNER_WORK_DIR: runnerWorkDir,
    RUNNER_TEMP: runnerTempDir,
    RUNNER_TOOL_CACHE: runnerToolCache,
    AGENT_TOOLSDIRECTORY: runnerToolCache,
    RUNNER_EPHEMERAL: "true",
    RUNNER_DISABLE_UPDATE: "true",
    DOCKER_HOST: "npipe:////./pipe/docker_engine"
  };

  if (pool.repositoryAccess === "selected") {
    environment.RUNNER_ALLOWED_REPOSITORIES = pool.allowedRepositories.join(",");
  }

  const service: Record<string, unknown> = {
    image: pool.imageRef,
    container_name: serviceName,
    hostname: serviceName,
    restart: "unless-stopped",
    stop_grace_period: "2m",
    environment,
    volumes: [
      `${runnerStateDir}:${runnerStateDir}`,
      {
        type: "npipe",
        source: "\\\\.\\pipe\\docker_engine",
        target: "\\\\.\\pipe\\docker_engine"
      }
    ],
    labels: {
      "com.github-runner-fleet.pool": pool.key,
      "com.github-runner-fleet.plane": "windows-docker",
      "com.github-runner-fleet.visibility": pool.visibility,
      "com.github-runner-fleet.repository-access": pool.repositoryAccess,
      "com.github-runner-fleet.allowed-repositories":
        pool.repositoryAccess === "all"
          ? "all"
          : pool.allowedRepositories.join(","),
      "com.github-runner-fleet.docker-capable": "true"
    }
  };

  if (pool.resources.cpus) {
    service.cpus = pool.resources.cpus;
  }

  if (pool.resources.pidsLimit !== undefined) {
    service.pids_limit = pool.resources.pidsLimit;
  }

  if (pool.resources.memory) {
    service.mem_limit = pool.resources.memory;
  }

  return service;
}

function formatIndex(index: number): string {
  return String(index + 1).padStart(2, "0");
}
